### PR TITLE
fix(core): :bug: adding important in padding

### PR DESCRIPTION
**Pull request by arkaprota**
## Description

The padding was not working previously in many places for that reason i have to add important in every padding property. in all files present in utility folder.

Ref: #102

``
p0: { padding: 0 + PX_TAG + IMPORTANT },
      p1: { padding: DEFAULT_PADDING + PX_TAG + IMPORTANT },
      p2: { padding: DEFAULT_PADDING * 2 + PX_TAG + IMPORTANT },
      p3: { padding: DEFAULT_PADDING * 3 + PX_TAG + IMPORTANT },
      p4: { padding: DEFAULT_PADDING * 4 + PX_TAG + IMPORTANT },
      p5: { padding: DEFAULT_PADDING * 5 + PX_TAG + IMPORTANT },

      pt0: { paddingTop: 0 + PX_TAG + IMPORTANT },
      pt1: { paddingTop: DEFAULT_PADDING + PX_TAG + IMPORTANT },
      pt2: { paddingTop: DEFAULT_PADDING * 2 + PX_TAG + IMPORTANT },
      pt3: { paddingTop: DEFAULT_PADDING * 3 + PX_TAG + IMPORTANT },
      pt4: { paddingTop: DEFAULT_PADDING * 4 + PX_TAG + IMPORTANT },
      pt5: { paddingTop: DEFAULT_PADDING * 5 + PX_TAG + IMPORTANT },

      pr0: { paddingRight: 0 + PX_TAG + IMPORTANT },
      pr1: { paddingRight: DEFAULT_PADDING + PX_TAG + IMPORTANT },
      pr2: { paddingRight: DEFAULT_PADDING * 2 + PX_TAG + IMPORTANT },
      pr3: { paddingRight: DEFAULT_PADDING * 3 + PX_TAG + IMPORTANT },
      pr4: { paddingRight: DEFAULT_PADDING * 4 + PX_TAG + IMPORTANT },
      pr5: { paddingRight: DEFAULT_PADDING * 5 + PX_TAG + IMPORTANT },

      pb0: { paddingBottom: 0 + PX_TAG + IMPORTANT },
      pb1: { paddingBottom: DEFAULT_PADDING + PX_TAG + IMPORTANT },
      pb2: { paddingBottom: DEFAULT_PADDING * 2 + PX_TAG + IMPORTANT },
      pb3: { paddingBottom: DEFAULT_PADDING * 3 + PX_TAG + IMPORTANT },
      pb4: { paddingBottom: DEFAULT_PADDING * 4 + PX_TAG + IMPORTANT },
      pb5: { paddingBottom: DEFAULT_PADDING * 5 + PX_TAG + IMPORTANT },

      pl0: { paddingLeft: 0 + PX_TAG + IMPORTANT },
      pl1: { paddingLeft: DEFAULT_PADDING + PX_TAG + IMPORTANT },
      pl2: { paddingLeft: DEFAULT_PADDING * 2 + PX_TAG + IMPORTANT },
      pl3: { paddingLeft: DEFAULT_PADDING * 3 + PX_TAG + IMPORTANT },
      pl4: { paddingLeft: DEFAULT_PADDING * 4 + PX_TAG + IMPORTANT },
      pl5: { paddingLeft: DEFAULT_PADDING * 5 + PX_TAG + IMPORTANT },

      px0: {
        paddingLeft : 0 + PX_TAG + IMPORTANT,
        paddingRight: 0 + PX_TAG + IMPORTANT,
      },
      px1: {
        paddingLeft : DEFAULT_PADDING * 1 + PX_TAG + IMPORTANT,
        paddingRight: DEFAULT_PADDING * 1 + PX_TAG,
      },
      px2: {
        paddingLeft : DEFAULT_PADDING * 2 + PX_TAG + IMPORTANT,
        paddingRight: DEFAULT_PADDING * 2 + PX_TAG + IMPORTANT,
      },
      px3: {
        paddingLeft : DEFAULT_PADDING * 3 + PX_TAG + IMPORTANT,
        paddingRight: DEFAULT_PADDING * 3 + PX_TAG,
      },
      px4: {
        paddingLeft : DEFAULT_PADDING * 4 + PX_TAG + IMPORTANT,
        paddingRight: DEFAULT_PADDING * 4 + PX_TAG + IMPORTANT,
      },
      px5: {
        paddingLeft : DEFAULT_PADDING * 5 + PX_TAG + IMPORTANT,
        paddingRight: DEFAULT_PADDING * 5 + PX_TAG + IMPORTANT,
      },

      py0: {
        paddingBottom: 0 + PX_TAG + IMPORTANT,
        paddingTop   : 0 + PX_TAG + IMPORTANT,
      },
      py1: {
        paddingBottom: DEFAULT_PADDING * 1 + PX_TAG + IMPORTANT,
        paddingTop   : DEFAULT_PADDING * 1 + PX_TAG + IMPORTANT,
      },
      py2: {
        paddingBottom: DEFAULT_PADDING * 2 + PX_TAG + IMPORTANT,
        paddingTop   : DEFAULT_PADDING * 2 + PX_TAG + IMPORTANT,
      },
      py3: {
        paddingBottom: DEFAULT_PADDING * 3 + PX_TAG + IMPORTANT,
        paddingTop   : DEFAULT_PADDING * 3 + PX_TAG + IMPORTANT,
      },
      py4: {
        paddingBottom: DEFAULT_PADDING * 4 + PX_TAG + IMPORTANT,
        paddingTop   : DEFAULT_PADDING * 4 + PX_TAG + IMPORTANT,
      },
      py5: {
        paddingBottom: DEFAULT_PADDING * 5 + PX_TAG + IMPORTANT,
        paddingTop   : DEFAULT_PADDING * 5 + PX_TAG + IMPORTANT,
      },
``

### CODE REVIEW

**Comment by arkaprota** [comment]
Please test this pull request
@techoneel

**Comment by arkaprota** [comment]
Do not merge it wright now there is a need of improvement of code here
@techoneel

**Comment by arkaprota** [comment]
the issue has been fixed please see through this and let me know if there is any changes needed or not
@techoneel

**Review by techoneel — COMMENTED** [review]
@arkaprota please review it with @samhere17

**Comment by wrappidcare** [comment]
Merging since stale over 24hrs.

**Comment by arkaprota** [comment]
Please check if there is any changes that is needed or not
@techoneel @samhere17

**Comment by wrappidcare** [comment]
Merging since stale over 24hrs.

**Pull request merged**
